### ISSUE TITLE
Pulseaudio dependancy needs to be changed

### ISSUE THREAD

**Issue by TheDigitalPixel** [scorpion-26/gBar#107]
*Please fill out this form and delete the defaults(everything not in bold font), so I can help you better*
**Describe the bug**

attempting to update pipewire-pulse package to 1:1.2.2-1 breaks dependency pulseaudio required by gbar-git. My system currently has pipewire-pulse 1:1.2.1-1. The effect is I am unable to do system updates without resolving this dependency.

**Steps to Reproduce**

What did you do, that triggered the issue? 

1. Run yay -S pipewire-pulse
2. install fails due to break in dependency

**Expected behavior**

gBar should get an updated dependency for pipewire-pulse as the new pipewire-pulse package no longer has pulseaudio. My understanding is pipewire-pulse replaces a deprecated pulseaudio. Asking for pipewire-pulse or pulseaudio would be better instead of asking only for pulseaudio.

**Screenshots/Error logs**

![2024-08-06T15:01:32,554910402-04:00](https://github.com/user-attachments/assets/d318b3eb-a55c-4d02-b968-a98a34ece835)

**Information about your system and gBar**
 - OS:Garuda (Arch)
 - Desktop environment Hyprland
 - commit sha256 if possible nan

**Comment by scorpion-26** [comment]
Should be already [fixed](https://aur.archlinux.org/packages/gbar-git#comment-985458). Just `yay -S gbar-git` and then update the system as normal.

**Comment by TheDigitalPixel** [comment]
I unfortunately tried this earlier. Just tried again and I still have the same issue.

**Comment by scorpion-26** [comment]
Have you made sure to clean build the package? If you have, does `pacman -R gbar-git && yay -S gbar-git` help? I also had this issue and the PKGBUILD update definitely fixed it for me, so my guess is that your is that pacman/yay hasn't recognized that the package dependencies changed.

**Comment by TheDigitalPixel** [comment]
Initially this did not work either, after some headbashing the issue is finally solved after I forced it with --redownload. Thanks for the help.
