### ISSUE TITLE
gtk4 support?

### ISSUE THREAD

**Issue by NullVoxPopuli** [scorpion-26/gBar#110]
I know gBar depends on gtk+-3.0 for building, but does that means it's incompatible with gtk4? (I'd rather not have multiple _sets_ of gtk* deps)

(I'm new to gtk stuff, apologies)

**Comment by scorpion-26** [comment]
gtk3 is not compatible with gtk4, as there are many breaking changes on the C API side. And since these changes aren't small things either, gtk4 would require some major rewrites. So unfortunately gBar will depend on gtk3 for the time being.
