### ISSUE TITLE
I can no longer install gBar

### ISSUE THREAD

**Issue by bluebyt** [scorpion-26/gBar#15]
**Describe the bug**
Since this commit below, I can no longer install gBar.

**Steps to Reproduce**
ninja -C build && sudo ninja -C build install

**Screenshots/Error logs**
https://pastebin.com/EvsDjQdp

**Information about your system and gBar**
 - OS: [Arch]
 - Desktop environment [Hyprland]
 - commit sha256 if possible [1c6cd3bd2b7bff9366ab1d7f90d99fb8037928c5]

**Comment by scorpion-26** [comment]
```git submodule update --init``` should do the trick

**Comment by bluebyt** [comment]
Yes it work!
