### ISSUE TITLE
can't compile it

### ISSUE THREAD

**Issue by Toni500github** [scorpion-26/gBar#16]
**Describe the bug**
i have all the dependencies, i run `meson setup build` then `ninja -C build` and it gives this error 
```
ninja: Entering directory `build'
[1/1] Linking target gBar
FAILED: gBar 
c++  -o gBar gBar.p/src_gBar.cpp.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -Wl,-rpath,XXXXXXXX -Wl,--start-group libgBar.a /usr/lib/x86_64-linux-gnu/libgtk-3.so /usr/lib/x86_64-linux-gnu/libgdk-3.so /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so /usr/lib/x86_64-linux-gnu/libpango-1.0.so /usr/lib/x86_64-linux-gnu/libharfbuzz.so /usr/lib/x86_64-linux-gnu/libatk-1.0.so /usr/lib/x86_64-linux-gnu/libcairo-gobject.so /usr/lib/x86_64-linux-gnu/libcairo.so /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so /usr/lib/x86_64-linux-gnu/libgio-2.0.so /usr/lib/x86_64-linux-gnu/libgobject-2.0.so /usr/lib/x86_64-linux-gnu/libglib-2.0.so /usr/lib/x86_64-linux-gnu/libgtk-layer-shell.so /usr/lib/x86_64-linux-gnu/libpulse.so /usr/local/lib/x86_64-linux-gnu/libwayland-client.so /usr/lib/x86_64-linux-gnu/libdbusmenu-gtk3.so /usr/lib/x86_64-linux-gnu/libdbusmenu-glib.so -Wl,--end-group
/usr/local/bin/ld: libgBar.a(src_System.cpp.o): undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/local/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed. 
```

**Steps to Reproduce**
1. `meson setup build`
2. `ninja -C build`
3. that's it

**Expected behavior**
it to be compiled

**Information about your system and gBar**
 - OS: Linuxmint 20.3 
 - Desktop environment: DWM
 - commit sha256: c51fadbc794ab5e4e8754b8f55775b83a0d80259

**Comment by scorpion-26** [comment]
> Desktop environment: DWM

gBar is a Wayland-only application and thus won't work with X11 compositors like dwm. You need a Wayland compositor like e.g. Hyprland or dwl (dwm port to wayland). 

It should compile if you run the following 
```
rm -rf build
LDFLAGS=-pthread meson setup build
ninja -C build
```
I can add the additional flag as default once it is confirmed, that this fixes it

**Comment by Toni500github** [comment]
ohh it's for wayland. dammit it was so cool.
btw i run to another issue similiar to this but fixed with `LDFLAGS='-pthread -ldl' meson setup build` instead of `LDFLAGS=-pthread meson setup build`
