### ISSUE TITLE
Feature request: confirmation buttons for shutdown, reboot...

### ISSUE THREAD

**Issue by LucaErr** [scorpion-26/gBar#17]
Hi ! Imo it could be nice to add a confirmation button for each power option (shutdown, reboot, log out etc...), 'cause a couple of time i shutdown the computer for mistake 😅. 
I hope that my request isn't an "idiot request".

**Comment by scorpion-26** [comment]
> I hope that my request isn't an "idiot request".

No, not at all. I've misclicked myself multiple times causing an annoying reboot. So, thanks for the suggestion to implement a better system.

Just pushed a commit which adds a confirmation step for all buttons in the Power slide out. When first clicked, the clicked button is made green and you need to click again within 2 seconds (when its still green) for the thing to happen. This is a bit ad-hoc, but it works.

**Comment by LucaErr** [comment]
sorry for the late reply ! Btw It seems to work really well, now i just need to add to my current css conf.

**Comment by scorpion-26** [comment]
Cool! If you have any other concerns, let me know.
