### ISSUE TITLE
Clicking the Bluetooth button multiple times opens multiple instances of the dropdown menu

### ISSUE THREAD

**Issue by SkyLeite** [scorpion-26/gBar#21]
Thank you for gBar, it looks and works great!

**Describe the bug**
When the Bluetooth button is clicked it does not check for the existence of the dropdown before opening a new one.

**Steps to Reproduce**
1. Click the Bluetooth button X number of times
2. Click the red X button to close the dropdown

**Expected behavior**
The dropdown should no longer be visible

**Observed behavior**
The dropdown menu continues to be visible until the red X button is clicked as many times as the Bluetooth button

**Screenshots/Error logs**
Irrelevant

**Information about your system and gBar**
 - OS: NixOS
 - Desktop environment: Hyprland
 - Commit hash: 18f3e123ed8e323b821fcbe8c44ca63011f8fd0c

**Comment by scorpion-26** [comment]
Thanks for the issue report. Should be fixed now with the above mentioned commit

**Comment by SkyLeite** [comment]
Thank you!
