### ISSUE TITLE
Disappearing Tray icons. 

### ISSUE THREAD

**Issue by kragebein** [scorpion-26/gBar#26]
*Please fill out this form and delete the defaults(everything not in bold font), so I can help you better*
**Describe the bug**
Tray icons not showing up. 

**Steps to Reproduce**
Installed gBar via yay, started gbar using `gBar bar 0`

Caprine and discord just dissapears after a short while, remmina doesnt show up at all. 
edit: fixed after copying remmina icon into search path of gBar.
Discord and Caprine icons just disappears. 

**Expected behavior**
Tray icons should disappear. 

**Screenshots/Error logs**
`
gBar bar 0
Set value for CPUThermalZone: /sys/devices/pci0000:00/0000:00:18.3/hwmon/hwmon2/temp1_input
Set value for SuspendCommand: ~/.config/scripts/sys.sh suspend
Set value for LockCommand: ~/.config/scripts/sys.sh lock
Set value for ExitCommand: killall Hyprland
Set value for BatteryFolder: /sys/class/power_supply/BAT0
Set value for DefaultWorkspaceSymbol: 
Set value for WorkspaceScrollOnMonitor: true
Set value for WorkspaceScrollInvert: false
Set value for UseHyprlandIPC: true
Set value for Location: T
Set value for CenterTime: true
Set value for TimeSpace: 300
Set value for DateTimeStyle: %a %D - %H:%M:%S
Set value for AudioInput: false
Set value for AudioRevealer: true
Set value for AudioScrollSpeed: 5
Set value for CheckPackagesCommand: p="$(checkupdates)"; e=$?; if [ $e -eq 127 ] ; then exit 127; fi; if [ $e -eq 2 ] ; then echo "0" && exit 0; fi; echo "$p" | wc -l
Set value for CheckUpdateInterval: 300
Set value for NetworkAdapter: wlan0
Set value for NetworkWidget: true
Set value for EnableSNI: true
Set value for SNIIconSize: *, 25
Set value for SNIIconSize: OBS, 23
Set value for MinDownloadBytes: 0
Set value for MaxDownloadBytes: 10485760
Set value for MinUploadBytes: 0
Set value for MaxUploadBytes: 5242880
Wayland: Added workspace!
Workspace ID: 10
Wayland: Deactivate Workspace 10
Wayland: Added workspace!
Workspace ID: 9
Wayland: Activate Workspace 9
Wayland: Added workspace!
Workspace ID: 3
Wayland: Deactivate Workspace 3
Wayland: Registering monitor DP-4 at ID 0
Wayland: Added group to monitor
Wayland: Registering monitor DP-5 at ID 1
Wayland: Added group to monitor
NVML not found, disabling Nvidia GPU
AMD GPU not found, disabling AMD GPU
PulseAudio: Context is ready!
PulseAudio: Update info
CSS found and loaded successfully!
SNI: Clearing old children
Invalid child!

(gBar:50878): Gtk-CRITICAL **: 12:05:41.876: gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed

(gBar:50878): Gtk-CRITICAL **: 12:05:41.876: gtk_range_set_value: assertion 'GTK_IS_RANGE (range)' failed
SNI: Registered Item org.kde.StatusNotifierItem-43838-1 /StatusNotifierItem
SNI: Registered Item org.kde.StatusNotifierItem-44229-1 /StatusNotifierItem
SNI: Registered Item :1.250 /StatusNotifierItem
SNI: Registered Item :1.15 /org/ayatana/NotificationItem/indicator_solaar
SNI: Registered Item :1.343 /org/ayatana/NotificationItem/remmina_icon
SNI: Registered Item :1.9 /org/ayatana/NotificationItem/nm_applet
SNI: Registered Item :1.17 /org/ayatana/NotificationItem/smsportal
SNI: Registered Item :1.7 /org/ayatana/NotificationItem/pasystray
SNI: Registered Item :1.393 /org/blueman/sni
SNI: Creating Item :1.7 /org/ayatana/NotificationItem/pasystray
SNI: Searching icon audio-volume-low in /home/stla/.local/share/flatpak/exports/share/icons
SNI: Searching icon audio-volume-low in /var/lib/flatpak/exports/share/icons
SNI: Searching icon audio-volume-low in /usr/local/share/icons
SNI: Searching icon audio-volume-low in /usr/share/icons
SNI: Menu object path: /org/ayatana/NotificationItem/pasystray/Menu
SNI: Creating Item :1.17 /org/ayatana/NotificationItem/smsportal
SNI: Menu object path: /org/ayatana/NotificationItem/smsportal/Menu
SNI: Creating Item :1.9 /org/ayatana/NotificationItem/nm_applet
SNI: Searching icon nm-signal-75 in /home/stla/.local/share/flatpak/exports/share/icons
SNI: Searching icon nm-signal-75 in /var/lib/flatpak/exports/share/icons
SNI: Searching icon nm-signal-75 in /usr/local/share/icons
SNI: Searching icon nm-signal-75 in /usr/share/icons
SNI: Menu object path: /org/ayatana/NotificationItem/nm_applet/Menu
SNI: Creating Item :1.343 /org/ayatana/NotificationItem/remmina_icon
SNI: Searching icon org.remmina.Remmina-status in /home/stla/.local/share/flatpak/exports/share/icons
SNI: Searching icon org.remmina.Remmina-status in /var/lib/flatpak/exports/share/icons
SNI: Searching icon org.remmina.Remmina-status in /usr/local/share/icons
SNI: Searching icon org.remmina.Remmina-status in /usr/share/icons
SNI: Menu object path: /org/ayatana/NotificationItem/remmina_icon/Menu
SNI: Creating Item :1.393 /org/blueman/sni
SNI: Searching icon blueman-tray in /home/stla/.local/share/flatpak/exports/share/icons
SNI: Searching icon blueman-tray in /var/lib/flatpak/exports/share/icons
SNI: Searching icon blueman-tray in /usr/local/share/icons
SNI: Searching icon blueman-tray in /usr/share/icons
SNI: Title: Bluetooth Enabled
SNI: Menu object path: /org/blueman/sni/menu
SNI: Creating Item :1.15 /org/ayatana/NotificationItem/indicator_solaar
SNI: Cannot open /usr/share/solaar/icons/battery-full-symbolic.png
SNI: Creating Item :1.250 /StatusNotifierItem
SNI: Width: 256
SNI: Height: 256
SNI: Title: 1Password
SNI: Menu object path: /com/canonical/dbusmenu
SNI: Creating Item org.kde.StatusNotifierItem-44229-1 /StatusNotifierItem
SNI: Width: 96
SNI: Height: 96
SNI: Title: Caprine
SNI: Menu object path: /com/canonical/dbusmenu
SNI: Creating Item org.kde.StatusNotifierItem-43838-1 /StatusNotifierItem
SNI: Width: 24
SNI: Height: 24
SNI: Title: Discord
SNI: Menu object path: /com/canonical/dbusmenu
SNI: Clearing old children
Destroy widget

(gBar:50878): Gtk-CRITICAL **: 12:05:43.003: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
SNI: Add :1.7 to widget
SNI: Add :1.17 to widget
SNI: Add :1.9 to widget
SNI: Add :1.343 to widget
SNI: Add :1.393 to widget
SNI: Add :1.250 to widget
SNI: Add org.kde.StatusNotifierItem-44229-1 to widget
SNI: Add org.kde.StatusNotifierItem-43838-1 to widget
Audio: Set volume of sink: 0.16
Audio: Set volume of sink: 0.2
Audio: Set volume of sink: 0.24
Audio: Set volume of sink: 0.29
Audio: Set volume of sink: 0.34
SNI: Reloading :1.7 /org/ayatana/NotificationItem/pasystray
SNI: Reloading org.kde.StatusNotifierItem-44229-1 /org/ayatana/NotificationItem/pasystray
SNI: Reloading org.kde.StatusNotifierItem-43838-1 /org/ayatana/NotificationItem/pasystray
Audio: Set volume of sink: 0.36
Audio: Set volume of sink: 0.37
SNI: Creating Item org.kde.StatusNotifierItem-43838-1 /org/ayatana/NotificationItem/pasystray
SNI: Unknown path!
SNI: Creating Item org.kde.StatusNotifierItem-44229-1 /org/ayatana/NotificationItem/pasystray
SNI: Unknown path!
SNI: Creating Item :1.7 /org/ayatana/NotificationItem/pasystray
SNI: Searching icon audio-volume-medium in /home/stla/.local/share/flatpak/exports/share/icons
SNI: Searching icon audio-volume-medium in /var/lib/flatpak/exports/share/icons
SNI: Searching icon audio-volume-medium in /usr/local/share/icons
SNI: Searching icon audio-volume-medium in /usr/share/icons
SNI: Menu object path: /org/ayatana/NotificationItem/pasystray/Menu
SNI: Clearing old children
Destroy widget

(gBar:50878): Gtk-CRITICAL **: 12:05:47.898: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
Destroy widget

(gBar:50878): Gtk-CRITICAL **: 12:05:47.898: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
Destroy widget

(gBar:50878): Gtk-CRITICAL **: 12:05:47.898: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
Destroy widget

(gBar:50878): Gtk-CRITICAL **: 12:05:47.899: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
Destroy widget

(gBar:50878): Gtk-CRITICAL **: 12:05:47.899: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
Destroy widget

(gBar:50878): Gtk-CRITICAL **: 12:05:47.899: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
Destroy widget

(gBar:50878): Gtk-CRITICAL **: 12:05:47.899: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
Destroy widget

(gBar:50878): Gtk-CRITICAL **: 12:05:47.899: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
Destroy widget

(gBar:50878): Gtk-CRITICAL **: 12:05:47.899: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
Destroy widget

(gBar:50878): Gtk-CRITICAL **: 12:05:47.899: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
Destroy widget

(gBar:50878): Gtk-CRITICAL **: 12:05:47.899: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
Destroy widget

(gBar:50878): Gtk-CRITICAL **: 12:05:47.899: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
Destroy widget

(gBar:50878): Gtk-CRITICAL **: 12:05:47.899: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
Destroy widget

(gBar:50878): Gtk-CRITICAL **: 12:05:47.899: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
Destroy widget

(gBar:50878): Gtk-CRITICAL **: 12:05:47.899: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
Destroy widget

(gBar:50878): Gtk-CRITICAL **: 12:05:47.899: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
Destroy widget

(gBar:50878): Gtk-CRITICAL **: 12:05:47.899: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
SNI: Add :1.17 to widget
SNI: Add :1.9 to widget
SNI: Add :1.343 to widget
SNI: Add :1.393 to widget
SNI: Add :1.250 to widget
SNI: Add :1.7 to widget
Audio: Set volume of sink: 0.37
Audio: Set volume of sink: 0.38
PulseAudio: Update info
`

**Information about your system and gBar**
 - OS: [Arch Linux]
 - Desktop environment [Hyprland]
 - commit fe7b02b10c872ce7cc9d32a292dcade56742a466

**Comment by scorpion-26** [comment]
Okay, I can reproduce the issue now, 39cf17c did in fact not patch it. Working on a proper fix now.

**Comment by scorpion-26** [comment]
Should be fixed now.

**Comment by kragebein** [comment]
That seems to do the trick! Thanks!

**Comment by kragebein** [comment]
Just tested it over time. 
Thanks for the quick fix. This now ensures that i switch permanently over to gbar from waybar :100:
