### ISSUE TITLE
Powerbutton not aligned.

### ISSUE THREAD

**Issue by kragebein** [scorpion-26/gBar#27]
Power button is not aligned. Using css from git. 

Arch Linux, Hyprland, commit fe7b02b10c872ce7cc9d32a292dcade56742a466

![Screenshot](https://github.com/scorpion-26/gBar/assets/19599766/e5557dc1-18da-49d0-a0dd-ee94504356b4)

**Comment by scorpion-26** [comment]
Do you have Caskaydia Cove NF installed? (https://www.nerdfonts.com/font-downloads)
If you have, do you have an up-to-date version?

**Comment by kragebein** [comment]
Embaressing, yes. That worked. thank you.
