### ISSUE TITLE
9th workspace indicator does not change color when filled or selected.

### ISSUE THREAD

**Issue by captainbanaynays** [scorpion-26/gBar#28]
**Describe the bug**
When using workspace 9, the icon that corresponds to it is unresponsive.

**Steps to Reproduce**
1. Open the bar
2. Select workspace 9 - no visual indicator of current workspace at all
3. Try to run an app and leave workspace - no indicator that workspace is currently full

**Expected behavior**
Color should change like the rest of the workspace icons.

**Screenshots/Error logs**
![2023-07-27-173506_hyprshot](https://github.com/scorpion-26/gBar/assets/22987660/4223c0dc-e7e1-4cfa-a941-580fcb1deb8d)
![2023-07-27-173531_hyprshot](https://github.com/scorpion-26/gBar/assets/22987660/592254fa-334b-447e-8874-635123378f2f)

**Information about your system and gBar**
 - OS: Arch
 - Desktop environment: Hyprland
 - commit sha256: fe7b02b10c872ce7cc9d32a292dcade56742a466

**Comment by scorpion-26** [comment]
Thanks for the report. Since I currently don't use Hyprland IPC, this issue wasn't on my mind, even though I've known about it for a long time 😅
