### ISSUE TITLE
cannot open shared object file:

### ISSUE THREAD

**Issue by jishnurajendran** [scorpion-26/gBar#3]
`gBar: error while loading shared libraries: libgBar.so: cannot open shared object file: No such file or directory`

this error when running `gBar bar 0`.

**Comment by scorpion-26** [comment]
If you've followed the install instructions:
```libgBar.so``` is found in ```/usr/local/lib```, which is not part of any of the dynamic linker search paths.

To fix that:
Put ```/usr/local/lib/``` at the end of ```/etc/ld.so.conf```, then reboot.
This should fix the problem.

**Comment by jishnurajendran** [comment]
Thanks, this works

**Comment by linuxmobile** [comment]
> Put `/usr/local/lib/` at the end of `/etc/ld.so.conf`, then reboot.

Same error here. 

I added this in both ways: `include /usr/local/lib` & `/usr/local/lib`
I rebooted both times but nothing. Follow the same error.
![image](https://user-images.githubusercontent.com/10554636/215337262-1150172a-2ce9-4501-a8e0-6155205ccb25.png)

**Comment by scorpion-26** [comment]
Can you post the output of ```lld /usr/local/bin/gBar```?
Does ```libgBar.so``` exist in ```/usr/local/lib/```?

**Comment by linuxmobile** [comment]
> ldd /usr/local/bin/gBar

Thx for answer so fast <3
![image](https://user-images.githubusercontent.com/10554636/215344731-1bda2be8-10f8-45c5-83ac-35a740e1aa82.png)

**Comment by scorpion-26** [comment]
Does running ```LD_LIBRARY_PATH=/usr/local/lib/ gBar bar 0``` work?

**Comment by linuxmobile** [comment]
> LD_LIBRARY_PATH=/usr/local/lib/ gBar bar 0

Yes. Running fine now:
![image](https://user-images.githubusercontent.com/10554636/215345459-3843a8cd-0033-4b28-8445-4ee47a1e281d.png)

**Comment by scorpion-26** [comment]
Strange...
Anyway, you can make that permanent by adding it ```LD_LIBRARY_PATH=/usr/local/lib/``` to ```/etc/environment```, then logout and it should work.

Note, that this could cause issues, since now the linker prefers the libraries ```/usr/local/lib``` over libraries in the same path as any executable. An alternative to setting ```LD_LIBRARY_PATH``` would be just installing to ```/usr``` instead of ```/usr/local/lib```: 
```meson setup build --reconfigure -Dbuildtype=release -Dprefix=/usr```, then compile and install as usual.
