### ISSUE TITLE
Cannot find plugin library!

### ISSUE THREAD

**Issue by Hfhdhdhf** [scorpion-26/gBar#33]
when i run the command
gBar 0
this happens

[ihatemyself@archlinux gBar]$ gBar 0
Failed opening config!
Wayland: Added workspace!
Workspace ID: 1
Wayland: Activate Workspace 1
Wayland: Registering monitor VGA-1 at ID 0
Wayland: Added group to monitor
Forcefully activate workspace 1
NVML not found, disabling Nvidia GPU
AMD GPU not found, disabling AMD GPU
Can't connect to BlueZ d-bus! Disabling Bluetooth!
GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit dbus-org.bluez.service not found.
PulseAudio: Context is ready!
PulseAudio: Update info
Cannot open network device! Disabling Network widget.
Info: No CSS found in /home/rafa/.config
Info: No CSS found in /home/rafa/.local/share
CSS found and loaded successfully!
Cannot find plugin library!
[Exiting due to assert failed]
[notgivingmyname@archlinux gBar]$ 

any fixes?

**Comment by scorpion-26** [comment]
```gBar 0``` is not a correct command.\
You need to specify, what to launch. 
e.g. ```gBar bar 0``` for the status bar or ```gBar audio 0``` for the audio widget.

**Comment by ShivanshuKantPrasad** [comment]
Maybe it should output better error message on incorrect commands?
