### ISSUE TITLE
Corrupted characters

### ISSUE THREAD

**Issue by Hfhdhdhf** [scorpion-26/gBar#34]
gBar corrupted characters

i opened gBar for the first time using
gBar bar 0 (after the owner helped me)
and the characters show like this

![image](https://github.com/scorpion-26/gBar/assets/120726073/eaf5893d-e7ee-4aea-9076-274a2d22a894)

any fixes?

**Comment by scorpion-26** [comment]
You need an up-to-date Nerd-Font (https://www.nerdfonts.com/).
gBar by default uses the Caskaydia-Cove NF, which can be installed with the ```ttf-cascadia-code-nerd``` Arch package (I assume you're on Arch). After that is installed, restart gBar and it *should* show the icons correctly.

If you want to use another Nerd-Font, you need to modify the css. A guide for that can be found in the FAQ section of the README ("FAQ/I want to customize the colors")

For further info you can also have a look at "FAQ/The icons are not showing!".
