### ISSUE TITLE
Feature Request - Options for Numbers Instead of Sliders

### ISSUE THREAD

**Issue by SnowPuppy429** [scorpion-26/gBar#35]
I am loving the project. It is so much lighter than Waybar. Very well done.

However, I do have some feature requests to have the same functionality that I have on Waybar. I am currently using a customized version of LinuxMobile's Waybar config, and these are some features that I would love to see in gBar.

I personally prefer to use numbers for my workspaces, brightness, microphone, and volume sliders.
![numbered_brightness,volume,microphone](https://github.com/scorpion-26/gBar/assets/105820137/ad7e5a4b-c8b9-4309-9b5b-bba68a38b5b6)
![numbered_workspaces](https://github.com/scorpion-26/gBar/assets/105820137/d068455b-77d1-47aa-a5cf-82eebd7bdf53)

I understand that this is a personal project so there is no shame in saying "no" to these features.

**Comment by scorpion-26** [comment]
Alright, should be implemented now. The option can be found under ```AudioNumbers```. Currently this only affects the bar and not the audio fly-in widget. If you want that to display numbers too, please let me know.

**Comment by SnowPuppy429** [comment]
Awesome. Thanks so much!
