### ISSUE TITLE
Teamviewer coredump

### ISSUE THREAD

**Issue by RochaLAJ** [scorpion-26/gBar#37]
**Describe the bug**
When i open Teamviewer, gBar crashes.

**Steps to Reproduce**
What did you do, that triggered the issue? 
1. Open the bar
2. Open Teamviewer
3. gBar crashes

**Expected behavior**
Keep teamviewer on tray 

**Screenshots/Error logs**
```
SNI: Searching icon TeamViewer in /var/lib/flatpak/exports/share/icons
SNI: Searching icon TeamViewer in /usr/local/share//icons
SNI: Searching icon TeamViewer in /usr/share//icons
GLib:ERROR:../glib/glib/gvariant-serialiser.c:1551:g_variant_serialised_n_children: code should not be reached
Bail out! GLib:ERROR:../glib/glib/gvariant-serialiser.c:1551:g_variant_serialised_n_children: code should not be reached
zsh: IOT instruction (core dumped)  gBar bar 0
```

**Information about your system and gBar**
 - OS: Arch
 - Desktop environment: Hyprland
 - commit 1a25dbdec692fa14bab9e3e18f00f959e8a927d8

**Comment by scorpion-26** [comment]
For some reason TeamViewer doesn't adhere to the StatusNotifierItem specification, which caused gBar to crash. I've just commited a workaround for that. TeamViewer should work as expected now.
