### ISSUE TITLE
Sensor texts go out of screen on hover.

### ISSUE THREAD

**Issue by linuxmobile** [scorpion-26/gBar#4]
I recorded a video so you can see the inconvenience!
https://youtu.be/rZIdxXfG_14

**Comment by scorpion-26** [comment]
I think this happens, when there isn't enough space for the text to appear and GTK resizes the window.
I don't know, if i can persuade GTK to not resize the window. 

Can you see if decreasing the font size(in the scss $textsize) fixes it?

I'll probably add an option, that replaces the revealers with tooltips in the future, which should also fix the issue.

**Comment by linuxmobile** [comment]
> I think this happens, when there isn't enough space for the text to appear and GTK resizes the window. I don't know, if i can persuade GTK to not resize the window.
> 
> Can you see if decreasing the font size(in the scss $textsize) fixes it?
> 
> I'll probably add an option, that replaces the revealers with tooltips in the future, which should also fix the issue.

Yeah. Decreasing the font size work but fs is 10px xD

**Comment by scorpion-26** [comment]
> Decreasing the font size work

Is the issue fixed, or does this workaround make the font way too small?

**Comment by linuxmobile** [comment]
> > Decreasing the font size work
> 
> Is the issue fixed, or does this workaround make the font way too small?

Is too small, but work fine xd

**Comment by scorpion-26** [comment]
I just added an option, which should fix the issue.
Just set ```CenterTime: false``` inside ~/.config/gBar/config(Like explained in the README)
Drawback is, that the time won't be centered anymore.

**Comment by linuxmobile** [comment]
> CenterTime: false

Fixed <3
