### ISSUE TITLE
Only 9/10 workspaces showing up 

### ISSUE THREAD

**Issue by RoccoRakete** [scorpion-26/gBar#45]
Pretty much what the title says. I'm using the stock config. 
Any fix for that?

**Comment by scorpion-26** [comment]
There's now a fix for that: Just specify ```NumWorkspaces: 10``` in the config.

Due to internal reasons, the syntax of ```WorkspaceSymbol``` changed in the process. If you use that config, you'd have to update it according to the example config found in ```data/config```
