### ISSUE TITLE
gBar compiles and runs very well in aarch64 - aur

### ISSUE THREAD

**Issue by Tpy0** [scorpion-26/gBar#47]
Just a heads up - when using makepkg, it throws an error about aarch64 and won't compile. When using makepkg -A it compiles and runs very well. Perhaps, aarch64 can be added to the list of architectures it will compile and run under. Thank you for gBar, it's my goto bar!

**Comment by scorpion-26** [comment]
Ok, thanks for the report. Updated PKGBUILD to include aarch64.
