### ISSUE TITLE
gBar fails to launch with std::out_of_range

### ISSUE THREAD

**Issue by ChristianWSmith** [scorpion-26/gBar#49]
**Describe the bug**
gBar fails to launch

**Steps to Reproduce**
1. Install gBar through Nix Home Manager like this:
  - [flake.nix](https://github.com/ChristianWSmith/nix-config/blob/92304029945b459b4c3a30befe437b64d131b27e/.config/home-manager/flake.nix#L15) lines 15, 18, 39
  - [home.nix](https://github.com/ChristianWSmith/nix-config/blob/92304029945b459b4c3a30befe437b64d131b27e/.config/home-manager/home.nix#L1) lines 1 and 26
  - [packages.nix](https://github.com/ChristianWSmith/nix-config/blob/92304029945b459b4c3a30befe437b64d131b27e/.config/home-manager/packages.nix#L37) lines 37-39
2. gBar bar 0

**Expected behavior**
gBar should open

**Screenshots/Error logs**
```
christian@nixos ~ (main)> gBar bar 0
Set value for AudioInput: false
Set value for AudioMaxVolume: 100
Set value for AudioMinVolume: 0
Set value for AudioNumbers: false
Set value for AudioRevealer: false
Set value for AudioScrollSpeed: 5
Set value for BatteryFolder: /sys/class/power_supply/BAT1
Set value for CPUThermalZone: /sys/devices/pci0000:00/0000:00:18.3/hwmon/hwmon2/temp1_input
Set value for CenterTime: true
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string_view::substr: __pos (which is 18446744073709551615) > __size (which is 1)
fish: Job 1, 'gBar bar 0' terminated by signal SIGABRT (Abort)
christian@nixos ~ (main) [SIGABRT]> 
```

**Information about your system and gBar**
 - OS: NixOS Unstable
 - Desktop environment: Hyprland
 - commit sha256: 0812c3680f054f5b1e2e92d58ff3e7befd0d0134

**Comment by scorpion-26** [comment]
Thanks for the bug. Should be fixed now. Problem was caused by the empty string ```DateTimeLocale: ``` generated by the nix module.
