### ISSUE TITLE
Feature request: custom icons

### ISSUE THREAD

**Issue by ThatOneCalculator** [scorpion-26/gBar#56]
Allowing the use of custom, non-nerdfont fonticons like [Phosphor](https://github.com/phosphor-icons/web/blob/master/src/bold/Phosphor-Bold.ttf) would be great :)

**Comment by scorpion-26** [comment]
Sorry for the long wait, but it should be implemented now.

**Comment by ThatOneCalculator** [comment]
Everything seems to work except the sleep button.

**Comment by ThatOneCalculator** [comment]
https://github.com/scorpion-26/gBar/assets/44733677/80764bec-ac0e-49df-b8fb-43d28fda90df

**Comment by ThatOneCalculator** [comment]
Also, being able to choose a custom icon for tray items like Discord would be nice.

![image](https://github.com/scorpion-26/gBar/assets/44733677/05e61dcf-0e77-4d31-9000-7d526e44e9cf)

![image](https://github.com/scorpion-26/gBar/assets/44733677/6d7b903f-8faf-420a-b845-0c33d68f830e)

**Comment by scorpion-26** [comment]
Sleep button should be fixed, expected the wrong thing in code

**Comment by ThatOneCalculator** [comment]
Awesome, fixed!
