### ISSUE TITLE
Guide about modules

### ISSUE THREAD

**Issue by Subhashis2007** [scorpion-26/gBar#61]
How can I enable, network and updater module?
Btw the bar is so nice, and solid, clean and plug n play. 
I prefer this more and using this,

**Comment by scorpion-26** [comment]
For the network widget you need to update the ```NetworkAdapter``` config variable to the id of your network card. The possible values can be found by ```ls /sys/class/net```. Common values include e.g. eno0, ... for lan; wlan0, wlp2s0, ... for wlan, lo for loopback(You probably don't want that). A guide on how to change the config can be found in the Readme.

For the package module, you need to install ```pacman-contrib``` if you are on Arch. Then it should work. For other distros you need to write the script/command yourself. The config variable for that is called ```CheckPackagesCommand```. The shell command should echo the number of packages that are not up to date.

**Comment by Subhashis2007** [comment]
Thanks for guiding me,
Tho I would suggest, if the network module could have an option for both ethernet and wifi toggle, so that we can just switch b/w them flawlessly.
