### ISSUE TITLE
[Feature Request] How about gradient animated borders??

### ISSUE THREAD

**Issue by Subhashis2007** [scorpion-26/gBar#65]
![2023-11-24-111116_hyprshot](https://github.com/scorpion-26/gBar/assets/113865986/115394e7-18bc-4493-9f5b-878a484784d2)

How nice would it be if the border of gBar would support gradients like hyprland windows do, it'll be an awesome uniform look. 

Thanks for this awesome project. Keep it up

**Comment by scorpion-26** [comment]
I mean that should already be possible with the css and the ```border-image``` property. Although this for some reason doesn't work for me. Anyways, this is something that GTK handles so there is not much I can implement/fix.

**Comment by Subhashis2007** [comment]
should I close this then?
