### ISSUE TITLE
left and center widget configuration

### ISSUE THREAD

**Issue by Soliprem** [scorpion-26/gBar#70]
In the css, one can edit .right to edit the whole of the right-aligned widgets. how does one do the same with left and center-aligned widgets? I tried .left, .center and variations, and they didn't work. 
Other than that, how does one handle the Workspace widget's background? I hacked at the css for a couple of hours to no avail

**Comment by Soliprem** [comment]
Trying to read the code, it seem that while right-hand-side widgets have 
``` right->SetClass("right");```, whilte left and center don't. This explains why there's no css field. However, my limited knowledge of c++ makes it impossible for me to try to implement the feature. Simply adding ```left->SetClass("left")``` to the equivalent position didn't break anything, but also didn't make it work

**Comment by Soliprem** [comment]
I have to be missing something, as I assume there has to be a way to control the Workspace widget's background.. @scorpion-26 is there a specific css field for it that I'm missing?

**Comment by scorpion-26** [comment]
There is not yet, CaptaiNiveau should be working on implementing this.

**Comment by Soliprem** [comment]
I would be willing to work with them to get it done. What parts of the code would need to be edited? I assume that most the work could be done by creating a box around the left-aligned widgets, but I can't quite get my bearings inside the project

**Comment by CaptaiNiveau** [comment]
Ah it's fine. I'll open a PR soon, you can check it out when it's there and tell us if you think there should be more classes.

I ran into this issue as well \^\^

**Comment by CaptaiNiveau** [comment]
@Soliprem You can check out my branch/repo and see if it suits your needs :)

**Comment by Soliprem** [comment]
works like a charm!
