### ISSUE TITLE
Telegram notification causes gBar to segfault

### ISSUE THREAD

**Issue by tupats** [scorpion-26/gBar#74]
**Describe the bug**

gBar crashes when receiving a Telegram notification.

**Steps to Reproduce**

1. Open the bar
2. Get Telegram notification
3. gBar crashes

**Expected behavior**

gBar shouldn't crash, but stay open

**Screenshots/Error logs**

`...
[Thread 0x7ffff1bfc6c0 (LWP 38105) exited]
SNI: Reloading :1.39 /StatusNotifierItem (Sender: :1.39)
SNI: Actual object path: /StatusNotifierItem
SNI: Delete static name buffer for :1.39
[New Thread 0x7ffff1bfc6c0 (LWP 38845)]
SNI: Creating Item :1.39 /StatusNotifierItem
SNI: Title: Telegram Desktop
SNI: Menu object path: /MenuBar

Thread 1 "gBar" received signal SIGSEGV, Segmentation fault.
0x00007ffff7e12f41 in g_type_check_instance_is_fundamentally_a ()
   from /usr/lib/libgobject-2.0.so.0`

**Information about your system and gBar**
 - Arch Linux, Hyprland, running swaync for notifications

**Comment by scorpion-26** [comment]
Should be fixed now
