### ISSUE TITLE
Feature: window title widget

### ISSUE THREAD

**Issue by fdev31** [scorpion-26/gBar#77]
It would be good to have a "window title" widget showing the active window's title.

Alternatively a "pipe" widget, which would take the information to display from a unix socket would do the job (and more) too.

**Comment by scorpion-26** [comment]
Done!
The widget name is ```Title```. If you want longer titles to be displayed, you can configure ```MaxTitleLength```. (Note that ```CenterSpace``` may need to be increased too.)

**Comment by fdev31** [comment]
That was fast! Thank you!

**Comment by fdev31** [comment]
Maybe not a bug, but I can't figure how to change the font (can make it bold etc, but couldn't set the family).

**Comment by scorpion-26** [comment]
The font is controlled by ```font-family``` in the css. AFAIK the font name is the same as the one you would input into e.g. vscode or the gtk settings ini.
