### ISSUE TITLE
Mouse wheel actions can break gBar on volume sliders

### ISSUE THREAD

**Issue by fdev31** [scorpion-26/gBar#86]
1. Use "wheel up" or "wheel down" in cycles for an abusive amount of time (~10s)
2. Observe gBar process the events in a very slow and lagging way

Result:

- volume is only changed after a long delay
- the slider bar isn't updated accordingly
- gBar may crash with `Gdk-Message: 09:59:43.394: Lost connection to Wayland compositor.`

Expectation option 1:

- snappy results, everything happening in real time

Expectation option 2:

- instead of queuing events, change the "strength" of the pending action, eg:

```C
mouse_up_handler() {
   pending_volume += INCREMENT;
   process_volume();
}

process_volume() {
   if (processing) return;
   start_processing_thread();
}

processing_thread() {
   while (actual_volume != pending_volume) {
      actual_volume = pending_volume;
      apply_volume();
   }
}

**Comment by scorpion-26** [comment]
Should be fixed now, so you can scroll as much as you want without freezing gBar
