### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by ZreXoc** [scorpion-26/gBar#94]
**Describe the bug**
Can't build gbar
What doesn't work? Please be as precise as possible.
**Steps to Reproduce**
run `paru -S gbar-git`

**Screenshots/Error logs**

see: [build.txt](https://github.com/scorpion-26/gBar/files/15277951/build.txt)

**Information about your system and gBar**
 - OS: Arch Linux x86_64 
 - DE: Hyprland, built from branch main at commit ed58cc4c31c21e09ee780d0df818afe935181cd9

**Comment by scorpion-26** [comment]
Fixed!
