### ISSUE TITLE
Audio flyin not disappearing properly

### ISSUE THREAD

**Issue by LAZAR-code** [scorpion-26/gBar#96]
The audio flyin is closing properly but not disappearing fully.
The audio flyin only disappears properly when the window behind it is refreshing.

Steps to Reproduce:
1. With default gBar config run "gBar audio"

Expected behavior:
gBar audio flyin should fully disappear after closing.

(I don't get any errors and gBar isn't chrashing)

Video of the bug:
https://imgur.com/a/pJRy492

 - OS: Arch
 - Desktop environment Hyprland

**Comment by scorpion-26** [comment]
This is most likely a bug with Hyprland's damage tracking, since this only happens after commit [93d05114](https://github.com/hyprwm/Hyprland/commit/93d05114716e847c37f49d3cc2d0c5cb01d06a24). 
I'll leave it open for now, until upstream is fixed.

**Comment by scorpion-26** [comment]
Alright, I decided to implement the much saner option of just letting the compositor do the job of the slide in/slide out animation. That should fix this issue.
