### ISSUE TITLE
Workspace indicators no longer highlighted for current workspace or open programs

### ISSUE THREAD

**Issue by TheDigitalPixel** [scorpion-26/gBar#97]
*Please fill out this form and delete the defaults(everything not in bold font), so I can help you better*
The workspace selector no longer highlights the current workspace or which workspaces have programs running. (No green dots, always grey)

What doesn't work? Please be as precise as possible.
e.g.: "gBar crashes on hovering the RAM sensor module. No other modules are affected."

using default style.css it's problematic on startup (running gBar bar 0 when hyprland starts)

What did you do, that triggered the issue? 
1. open gBar
2. switching workspaces or opening programs or moving programs
3. workspace indicators show no visual change (all grey)

What do you expect should happen?
e.g.: gBar shouldn't crash, but stay open

![2024-05-20T22:30:25,092673059-04:00](https://github.com/scorpion-26/gBar/assets/20602740/b9a52f2f-03d3-4ccc-ace1-0538f5d7061c)
as you can see all the dots are grey regardless of which workspace I am on or where programs are running. Some dots should be green to show current workspace or open programs. Colors are default.

Please include as much information about the crash/bug as possible.
 - If it is a visual glitch, please include a screenshot/video as well as any modifications to the css (if any).
 - If it is a *crash* (e.g. ```Segmentation fault (Core dumped)``` in the console), please include the log (```/tmp/gBar-<pid>.log``` or from the console) and a crash stack trace. They can e.g. be found via journalctl (```journalctl --boot=0 --reverse```) if systemd-coredump is used.
 - If it is an *assert failed* (Last line in the log reads ```[Exiting due to assert failed]```) please include the log (```/tmp/gBar-<pid>.log``` or from the console).
 - The config (```~/.config/gBar/config```) used is always valuable to diagnose an issue, so please include it.
 
config file:
[gbarconf.txt](https://github.com/scorpion-26/gBar/files/15383751/gbarconf.txt)

 - OS: Garuda Linux (Arch)
 - Desktop environment Hyprland

**Comment by scorpion-26** [comment]
If the command output is filled with the following, then please update gBar. Hyprland recently changed the IPC socket, breaking the workspace widget.
```
Couldn't connect to Hyprland socket.
RetrySocketOp: connect failed with -1
```

If there isn't such a thing in the logs, please include them here.

**Comment by TheDigitalPixel** [comment]
You were correct, launching a second instance from the terminal had that error message. Manually updating from AUR fixed the issue.
